#version: '3.3'
#
#services:
#  db:
#    image: mysql:5.7
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: spring_boot_jwt
#    ports:
#      - '3308:3306'
#    volumes:
#      - spring-boot-jwt-db:/var/lib/mysql
#
#  db_test:
#    image: mysql:5.7
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: test
#    ports:
#      - '3309:3306'
#    volumes:
#      - spring-boot-jwt-test-db:/var/lib/mysql
#
#  springboot-app:
#    # container_name: spring-app
#    image: springboot-app
#    restart: always
#    build: .
#    ports:
#      - '8000-8999:8090'
#    environment:
#      MYSQL_HOST: mysqldb
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_PORT: 3306
#
#
#volumes:
#  spring-boot-jwt-db:
#  spring-boot-jwt-test-db:


version: "3.3"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./spring-jwt
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: